# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
create_IMABC <- function(N0, Nc, Ngoal, B, target_sd_in, alpha_start_in, alpha_goal_in) {
    invisible(.Call(`_microcancer_create_IMABC`, N0, Nc, Ngoal, B, target_sd_in, alpha_start_in, alpha_goal_in))
}

#' @export
check_sim <- function(x) {
    .Call(`_microcancer_check_sim`, x)
}

#' @export
create_IMABC_one_node <- function(N0, Nc, Ngoal, B, target_sd_in, alpha_start_in, alpha_goal_in) {
    invisible(.Call(`_microcancer_create_IMABC_one_node`, N0, Nc, Ngoal, B, target_sd_in, alpha_start_in, alpha_goal_in))
}

#' @export
check_sim_one_node <- function(x) {
    .Call(`_microcancer_check_sim_one_node`, x)
}

#' @export
create_IMABC_two_node <- function(N0, Nc, Ngoal, B, target_sd_in, alpha_start_in, alpha_goal_in) {
    invisible(.Call(`_microcancer_create_IMABC_two_node`, N0, Nc, Ngoal, B, target_sd_in, alpha_start_in, alpha_goal_in))
}

#' @export
check_sim_two_node <- function(x) {
    .Call(`_microcancer_check_sim_two_node`, x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_microcancer_RcppExport_registerCCallable', PACKAGE = 'microcancer')
})
