# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
create_IMABC <- function() {
    invisible(.Call(`_microcancer_create_IMABC`))
}

#' @export
check_sim <- function() {
    .Call(`_microcancer_check_sim`)
}

#' @export
ab_work_together <- function() {
    invisible(.Call(`_microcancer_ab_work_together`))
}

#' @export
trial_read_csv_and_schedule_cancer <- function() {
    invisible(.Call(`_microcancer_trial_read_csv_and_schedule_cancer`))
}

squared_dist_vec <- function(v1, v2) {
    .Call(`_microcancer_squared_dist_vec`, v1, v2)
}

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_microcancer_dmvnrm_arma`, x, mean, sigma, logd)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_microcancer_RcppExport_registerCCallable', PACKAGE = 'microcancer')
})
